name: Run versionist action
on:
  push:
    branches:
      - master

jobs:

  versionist:
    if: "!contains(github.event.head_commit.author.name, 'versionist')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run balena-versionist
      uses: tmigone/versionist@master
      with:
        github_email: 'tmigone.versionist@gmail.com'
        github_username: 'versionist'
        github_token: ${{ secrets.GH_VERSIONIST_TOKEN }}